# Generated by Django 5.2.6 on 2026-03-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='notes',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
    ]
